//! Small Hyper body helpers.
//!
//! Hyper 1 exposes body types as traits rather than a single concrete response
//! body. Outgate mostly needs empty, fully-buffered, and channel-backed
//! streaming responses, so this module hides the `http-body-util` details
//! behind tiny local helpers.

use bytes::Bytes;
use futures_util::{Stream, TryStreamExt};
use http_body_util::{
    BodyExt, Channel, Empty, Full, StreamBody, channel, combinators::UnsyncBoxBody,
};
use hyper::Response;
use hyper::body::Frame;
use hyper::header::CONTENT_TYPE;
use hyper::http::StatusCode;
use std::convert::Infallible;
use std::error::Error;

pub type BodyError = Box<dyn Error + Send + Sync>;
pub type ResBody = UnsyncBoxBody<Bytes, BodyError>;
pub type ResBodySender = channel::Sender<Bytes, BodyError>;

/// Build a response with no body.
///
/// Used for successful `CONNECT` acknowledgement, where the upgraded socket
/// carries the real TLS traffic after the `200 OK`.
pub fn empty_response(status: StatusCode) -> Response<ResBody> {
    Response::builder()
        .status(status)
        .body(empty_body())
        .expect("valid empty response")
}

/// Build a plain-text response.
///
/// This is used for local admin endpoints and error responses generated by the
/// proxy itself, not for upstream responses.
pub fn text_response(status: StatusCode, body: impl Into<Bytes>) -> Response<ResBody> {
    Response::builder()
        .status(status)
        .header(CONTENT_TYPE, "text/plain; charset=utf-8")
        .body(full_body(body))
        .expect("valid text response")
}

/// Empty boxed body.
pub fn empty_body() -> ResBody {
    Empty::<Bytes>::new()
        .map_err(infallible_to_body_error)
        .boxed_unsync()
}

/// Fully buffered boxed body.
pub fn full_body(bytes: impl Into<Bytes>) -> ResBody {
    Full::new(bytes.into())
        .map_err(infallible_to_body_error)
        .boxed_unsync()
}

/// Channel-backed streaming body.
///
/// The sender side is held by the producer task. Hyper polls the boxed body and
/// sends chunks to the client as the producer pushes them.
pub fn channel_body(buffer: usize) -> (ResBodySender, ResBody) {
    let (sender, body) = Channel::<Bytes, BodyError>::new(buffer);
    (sender, body.boxed_unsync())
}

/// Stream-backed response body.
pub fn stream_body<S>(stream: S) -> ResBody
where
    S: Stream<Item = Result<Bytes, BodyError>> + Send + 'static,
{
    StreamBody::new(stream.map_ok(Frame::data)).boxed_unsync()
}

fn infallible_to_body_error(never: Infallible) -> BodyError {
    match never {}
}
